apiVersion: v1
kind: Service
metadata:
  name: nodeaks-api
  namespace: nodeapi
spec:
  type: LoadBalancer
  selector:
    app: nodeaks-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
